# Generated by Django 3.2.18 on 2023-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0036_merge_20210706_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_expirable',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as expirable. ', verbose_name='expirable'),
        ),
    ]
