# Generated by Django 3.2.18 on 2023-04-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0039_auto_20220506_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadparallelismlimit',
            name='max_number',
            field=models.PositiveSmallIntegerField(default=5, help_text='The maximum number of parallel uploads (0 to 32767).'),
        ),
    ]
