# Generated by Django 3.2.18 on 2023-04-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0041_alter_uploadparallelismlimit_max_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadparallelismlimit',
            name='max_number',
            field=models.PositiveSmallIntegerField(default=5, help_text='The maximum number of parallel uploads (0 to 32767).'),
        ),
    ]
